feat: add build action to mvn-build

diff --git a/.github/workflows/mvn-build-snapshot.yml b/.github/workflows/mvn-build-snapshot.yml
--- a/.github/workflows/mvn-build-snapshot.yml
+++ b/.github/workflows/mvn-build-snapshot.yml
@@ -3,8 +3,17 @@ on:
   workflow_call:
 
 jobs:
+  check_pr:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if PR
+        if: ${{ github.event_name != 'pull_request' }}
+        run: |
+          echo "::error::This workflow can only be run on pull_request events."
+          exit 1
   lint_commits:
     runs-on: ubuntu-latest
+    needs: check_pr
     steps:
       - name: Lint commits
         uses: actions-ecosystem/action-lint-commits@v1
@@ -38,4 +47,28 @@ jobs:
             ✔️ Lint passed.
       - name: Fail when commits don't pass lint
         if: ${{ steps.lint-commits.outputs.unmatched_commits != '' }}
-        run: exit 1
+        run: |
+          echo "::error::Commit messages don't pass lint, check the comment on the PR for more details."
+          exit 1
+  mvn-build-java:
+    runs-on: ubuntu-latest
+    needs: lint_commits
+    env:
+      REVISION: ${{ github.event.pull_request.head.ref }}-SNAPSHOT
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v1
+        with:
+          distribution: 'corretto'
+          java-version: 17
+          cache: 'maven'
+      - name: Build with Maven
+        run: mvn -Drevision="${{ env.REVISION }}" -B clean package --file pom.xml
+      - name: Compress build artifact
+        run: cd target; zip -r ../target.zip *
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ env.REVISION }}
+          path: target.zip
